// WorldDatabaseExporter.cs
// Copyright (c) 50PSoftware

namespace GameEngineTools.World.Data
{
    using System;
    using System.Globalization;
    using System.Text;

    /// <summary>
    /// Exports the current contents of a <see cref="SqliteWorldDatabase"/> as
    /// SQL INSERT statements compatible with <c>seed_data.sql</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>Typical workflow:</b>
    /// <list type="number">
    ///   <item>Seed the database from CSV files (one-time migration).</item>
    ///   <item>Call <see cref="ExportSeedSql"/> and save the output to
    ///   <c>GameEngineTools/World/Data/SQL/seed_data.sql</c>.</item>
    ///   <item>Add the file as <c>EmbeddedResource</c> in the .csproj.</item>
    ///   <item>Delete the CSV source files.</item>
    /// </list>
    /// </para>
    /// <para>
    /// All generated statements use <c>INSERT OR IGNORE</c> so the file is
    /// safe to re-run against a database that already contains data.
    /// </para>
    /// </remarks>
    public static class WorldDatabaseExporter
    {
        #region Public API

        /// <summary>
        /// Exports all world data from the database as a SQL seed script.
        /// The output is ready to be saved as <c>seed_data.sql</c>.
        /// </summary>
        /// <param name="db">Source database to export from.</param>
        /// <param name="terrainDb">
        /// Database to read the heightmap from — terrain now lives in its own dedicated database
        /// (see <see cref="WorldDatabaseSeeder.InitializeTerrainDatabase"/>), separate from
        /// <paramref name="db"/>'s Locations/Connections/WorldObjects. Defaults to <paramref name="db"/>
        /// itself for backward compatibility with callers that still keep both in one file.
        /// </param>
        /// <returns>Complete SQL seed script as a UTF-8 string.</returns>
        public static string ExportSeedSql(SqliteWorldDatabase db, SqliteWorldDatabase? terrainDb = null)
        {
            ArgumentNullException.ThrowIfNull(db);

            var sb = new StringBuilder();

            AppendHeader(sb);
            AppendSocialNorms(sb, db);
            AppendLocations(sb, db);
            AppendConnections(sb, db);
            AppendTerrainHeightmap(sb, terrainDb ?? db);
            AppendWorldObjects(sb, db);

            return sb.ToString();
        }

        #endregion Public API

        #region Private — section builders

        private static void AppendHeader(StringBuilder sb)
        {
            sb.AppendLine("-- seed_data.sql");
            sb.AppendLine($"-- Generated by WorldDatabaseExporter on {DateTime.UtcNow:yyyy-MM-ddTHH:mm:ssZ}");
            sb.AppendLine("-- Copyright (c) 50PSoftware");
            sb.AppendLine("--");
            sb.AppendLine("-- All statements use INSERT OR IGNORE — safe to re-run.");
            sb.AppendLine();
        }

        private static void AppendSocialNorms(StringBuilder sb, SqliteWorldDatabase db)
        {
            var norms = db.GetAllSocialNorms();
            if (norms.Count == 0) return;

            sb.AppendLine("-- ── Social Norms ────────────────────────────────────────────────────────────");
            sb.AppendLine();

            foreach (var n in norms)
            {
                sb.AppendLine(
                    $"INSERT OR IGNORE INTO SocialNorms " +
                    $"(Id, DisplayName, Kind, Severity, EnforcementProbability, " +
                    $"RelationalModel, CultureId, ValidFromYear, ValidToYear) VALUES " +
                    $"({Str(n.Id)}, {Str(n.DisplayName)}, {Str(n.Kind)}, " +
                    $"{R(n.Severity)}, {R(n.EnforcementProbability)}, " +
                    $"{Str(n.RelationalModel)}, {Str(n.CultureId)}, " +
                    $"{(n.ValidFromYear.HasValue ? n.ValidFromYear.Value.ToString() : "NULL")}, " +
                    $"{(n.ValidToYear.HasValue ? n.ValidToYear.Value.ToString() : "NULL")});");
            }

            sb.AppendLine();
        }

        private static void AppendLocations(StringBuilder sb, SqliteWorldDatabase db)
        {
            var locations = db.GetAllLocations();
            if (locations.Count == 0) return;

            sb.AppendLine("-- ── Locations ───────────────────────────────────────────────────────────────");
            sb.AppendLine();

            foreach (var (d, region) in locations)
            {
                sb.AppendLine(
                    $"INSERT OR IGNORE INTO Locations " +
                    $"(Id, DisplayName, Type, Region, BaseNoise, NoisePerPerson, " +
                    $"Capacity, AllowsPrivacy, Terrain, DangerLevel, AllowsPickup, NormId, X, Y, AltitudeMeters, " +
                    $"TemperatureCelsius, Humidity) VALUES " +
                    $"({Str(d.Id)}, {Str(d.DisplayName)}, {Str(d.Type.ToString())}, {Str(region)}, " +
                    $"{R(d.BaseNoise)}, {R(d.NoisePerPerson)}, " +
                    $"{d.Capacity}, {B(d.AllowsPrivacy)}, {Str(d.Terrain.ToString())}, " +
                    $"{R(d.DangerLevel)}, {B(d.AllowsPickup)}, {Str(d.NormId)}, {R(d.X)}, {R(d.Y)}, {R(d.AltitudeMeters)}, " +
                    $"{R(d.TemperatureCelsius)}, {R(d.Humidity)});");
            }

            sb.AppendLine();
        }

        private static void AppendTerrainHeightmap(StringBuilder sb, SqliteWorldDatabase db)
        {
            // Single default grid for now — see project plan for the multi-grid extension point.
            var grid = db.LoadHeightmap("default");
            if (grid is null) return;

            sb.AppendLine("-- ── Terrain Heightmap ───────────────────────────────────────────────────────");
            sb.AppendLine();
            sb.AppendLine(
                $"INSERT OR IGNORE INTO TerrainHeightmap " +
                $"(Id, OriginX, OriginY, CellSizeMeters, Width, Height, Data, RiverMask) VALUES " +
                $"({Str(grid.Id)}, {R(grid.OriginX)}, {R(grid.OriginY)}, {R(grid.CellSizeMeters)}, " +
                $"{grid.Width}, {grid.Height}, {Blob(grid.ToBytes())}, " +
                $"{(grid.RiverMask is null ? "NULL" : Blob(grid.RiverMask))});");
            sb.AppendLine();
        }

        private static void AppendConnections(StringBuilder sb, SqliteWorldDatabase db)
        {
            var connections = db.GetAllConnections();
            if (connections.Count == 0) return;

            sb.AppendLine("-- ── Connections ─────────────────────────────────────────────────────────────");
            sb.AppendLine();

            foreach (var (fromId, toId, distance) in connections)
            {
                sb.AppendLine(
                    $"INSERT OR IGNORE INTO Connections (FromId, ToId, DistanceMeters) VALUES " +
                    $"({Str(fromId)}, {Str(toId)}, {R(distance)});");
            }

            sb.AppendLine();
        }

        private static void AppendWorldObjects(StringBuilder sb, SqliteWorldDatabase db)
        {
            var objects = db.GetAllObjects();
            if (objects.Count == 0) return;

            sb.AppendLine("-- ── World Objects ───────────────────────────────────────────────────────────");
            sb.AppendLine();

            foreach (var obj in objects)
            {
                // Main object row
                sb.AppendLine(
                    $"INSERT OR IGNORE INTO WorldObjects " +
                    $"(Id, DisplayName, Category, LocationId, HeatSignature, AmbientNoise, " +
                    $"BlocksLineOfSight, IsAvailable, IsPickable, WeightGrams, ItemKind, " +
                    $"Respawns, RespawnMinutes, HeldBy) VALUES " +
                    $"({Str(obj.Id)}, {Str(obj.DisplayName)}, {Str(obj.Category.ToString())}, " +
                    $"{Str(obj.LocationId)}, {R(obj.HeatSignature)}, {R(obj.AmbientNoise)}, " +
                    $"{B(obj.BlocksLineOfSight)}, {B(obj.IsAvailable)}, {B(obj.IsPickable)}, " +
                    $"{obj.WeightGrams}, {Str(obj.ItemKind.ToString())}, " +
                    $"{B(obj.Respawns)}, {obj.RespawnMinutes}, " +
                    $"{(obj.HeldBy.HasValue ? Str(obj.HeldBy.Value.Value.ToString()) : "NULL")});");

                // Affordances
                foreach (var affordance in obj.Affordances)
                {
                    sb.AppendLine(
                        $"INSERT OR IGNORE INTO Affordances (ObjectId, Type, Satisfaction) VALUES " +
                        $"({Str(obj.Id)}, {Str(affordance.Type.ToString())}, {R(affordance.Satisfaction)});");
                }

                // Nutritional profile
                if (obj.NutritionalProfile is { } np)
                {
                    sb.AppendLine(
                        $"INSERT OR IGNORE INTO NutritionalProfiles " +
                        $"(ObjectId, CalorieGain, ProteinGain, IronGain, VitaminDGain, HydrationGain, " +
                        $"HemeIronFraction, VitaminCMilligrams) VALUES " +
                        $"({Str(obj.Id)}, {N(np.CalorieGain)}, {N(np.ProteinGain)}, " +
                        $"{N(np.IronGain)}, {N(np.VitaminDGain)}, {N(np.HydrationGain)}, " +
                        $"{N(np.HemeIronFraction)}, {N(np.VitaminCMilligrams)});");
                }
            }
        }

        #endregion Private — section builders

        #region Private — SQL value formatters

        /// <summary>Formats a string value as a quoted SQL literal with escaped single quotes.</summary>
        private static string Str(string? value)
            => value is null ? "NULL" : $"'{value.Replace("'", "''")}'";

        /// <summary>Formats a double as a SQL REAL literal with invariant culture.</summary>
        private static string R(double value)
            => value.ToString("G", CultureInfo.InvariantCulture);

        /// <summary>Formats a bool as a SQL INTEGER (0 or 1).</summary>
        private static string B(bool value)
            => value ? "1" : "0";

        /// <summary>Formats a nullable double as NULL or a REAL literal.</summary>
        private static string N(double? value)
            => value.HasValue ? R(value.Value) : "NULL";

        /// <summary>Formats a byte array as a SQLite BLOB literal (<c>X'...'</c>).</summary>
        private static string Blob(byte[] bytes)
            => "X'" + Convert.ToHexString(bytes) + "'";

        #endregion Private — SQL value formatters
    }
}
