// CoreLog.cs
// Copyright (c) 50PSoftware

namespace GameEngineTools.Logging
{
    using System;
    using Microsoft.Extensions.Logging;

    /// <summary>
    /// Central logging methods for GameEngineTools — generated by a source generator.
    /// </summary>
    /// <remarks>
    /// <para>
    /// All methods are generated via the <c>[LoggerMessage]</c> source generator,
    /// which guarantees <b>zero allocations</b> at runtime and compile-time parameter checking.
    /// </para>
    /// <para>
    /// <b>EventId range conventions:</b>
    /// <list type="table">
    ///   <item><term>1000–1999</term><description>Behavior — decisions, sleep, interactions</description></item>
    ///   <item><term>2000–2999</term><description>Relationships — vztahy, decay</description></item>
    ///   <item><term>3000–3999</term><description>Memory — episodic memory, consolidation</description></item>
    ///   <item><term>4000–4999</term><description>Infrastruktura — Scheduler, hosting</description></item>
    ///   <item><term>5000–5999</term><description>Snapshoty — Physiology / Psychology / Behavior (diagnostika)</description></item>
    /// </list>
    /// </para>
    /// </remarks>
    public static partial class CoreLog
    {
        #region Physiology

        /// <summary>Snapshot of the character's physiological state — logged every tick.</summary>
        [LoggerMessage(
            EventId = 5000,
            Level = LogLevel.Information,
            Message = "[PHYSIO] {HumanId} Energy:{Energy:F1} Hunger:{Hunger:F2} Thirst:{Thirst:F2} Pain:{Pain:F1} SleepDebt:{SleepDebt:F1}h Temp:{TempDelta:+0.0;-0.0}°C Immune:{Immune:F1} Allostatic:{Allostatic:F1} Cortisol:{Cortisol:F1} Testo:{Testosterone:F1} Cal:{Calories:F0} VitD:{VitaminD:F0} Iron:{Iron:F0} Prot:{Protein:F0} Gluc:{Glucose:F0} Grey:{Grey:F2} Wrinkle:{Wrinkle:F0} Hair:{HairDensity:F2} Muscle:{Muscle:F2} Bone:{Bone:F2}")]
        public static partial void PhysiologySnapshot(
            this ILogger logger,
            string HumanId,
            double Energy,
            double Hunger,
            double Thirst,
            double Pain,
            double SleepDebt,
            double TempDelta,
            double Immune,
            double Allostatic,
            double Cortisol,
            double Testosterone,
            double Calories,
            double VitaminD,
            double Iron,
            double Protein,
            double Glucose,
            double Grey,
            double Wrinkle,
            double HairDensity,
            double Muscle,
            double Bone);

        /// <summary>Current phase of the character's menstrual cycle.</summary>
        [LoggerMessage(
            EventId = 5001,
            Level = LogLevel.Debug,
            Message = "[PHYSIO/CYCLE] {HumanId} Phase:{Phase} Day:{DayInCycle} Libido:{Libido:F2} Ovul:{Ovulation} Pain:{Pain:F0} Bloat:{Bloat:F0} Tender:{Tender:F0} PMDD:{Pmdd}")]
        public static partial void PhysiologyCycle(
            this ILogger logger,
            string HumanId,
            string Phase,
            int DayInCycle,
            double Libido,
            bool Ovulation,
            double Pain,
            double Bloat,
            double Tender,
            bool Pmdd);

        /// <summary>Sleep ended — logs duration, quality, and remaining sleep debt after recovery.</summary>
        [LoggerMessage(EventId = 5002,
            Level = LogLevel.Debug,
            Message = "[PHYSIO/SLEEP] {HumanId} SleepEnded — délka: {Hours:F1}h, kvalita: {Quality:F0}, dluh po obnově: {Debt:F2}h.")]
        public static partial void PhysiologySleepEnded(this ILogger logger, string HumanId, double Hours, double Quality, double Debt);

        /// <summary>Conception was evaluated after an encounter — logs chance, fertility window and result.</summary>
        [LoggerMessage(
            EventId = 5003,
            Level = LogLevel.Debug,
            Message = "[PHYSIO/REPRO] {HumanId} conception evaluated with {OtherParent}: chance={Chance:F3}, ovulation={OvulationWindow}, intent={Intent}, contraception={Contraception}, result={Result}.")]
        public static partial void PhysiologyConceptionEvaluated(
            this ILogger logger,
            string HumanId,
            string OtherParent,
            double Chance,
            bool OvulationWindow,
            string Intent,
            string Contraception,
            string Result);

        /// <summary>Pregnancy started — logs the other parent and estimated due date.</summary>
        [LoggerMessage(
            EventId = 5004,
            Level = LogLevel.Information,
            Message = "[PHYSIO/REPRO] {HumanId} pregnancy started with otherParent={OtherParent}, due={EstimatedDueDate}.")]
        public static partial void PhysiologyPregnancyStarted(
            this ILogger logger,
            string HumanId,
            string OtherParent,
            string EstimatedDueDate);

        /// <summary>Pregnancy was discovered by the character — logs days pregnant.</summary>
        [LoggerMessage(
            EventId = 5005,
            Level = LogLevel.Information,
            Message = "[PHYSIO/REPRO] {HumanId} pregnancy discovered, otherParent={OtherParent}, daysPregnant={DaysPregnant}.")]
        public static partial void PhysiologyPregnancyDiscovered(
            this ILogger logger,
            string HumanId,
            string OtherParent,
            long DaysPregnant);

        /// <summary>A child was born — logs the other parent, conception date and due date.</summary>
        [LoggerMessage(
            EventId = 5006,
            Level = LogLevel.Information,
            Message = "[PHYSIO/REPRO] {HumanId} child born, otherParent={OtherParent}, conceivedOn={ConceivedOn}, due={EstimatedDueDate}.")]
        public static partial void PhysiologyChildBorn(
            this ILogger logger,
            string HumanId,
            string OtherParent,
            string ConceivedOn,
            string EstimatedDueDate);

        /// <summary>A character died of natural causes during the physiology tick.</summary>
        [LoggerMessage(
            EventId = 5007,
            Level = LogLevel.Warning,
            Message = "[PHYSIO/DEATH] {HumanId} died of {Cause} at age {Age} (risk/h={Risk:F5}).")]
        public static partial void NaturalDeathOccurred(
            this ILogger logger,
            string HumanId,
            string Cause,
            int Age,
            double Risk);

        #endregion Physiology

        #region Psychology

        /// <summary>Snapshot of the character's psychological state — logged every tick.</summary>
        [LoggerMessage(
            EventId = 5100,
            Level = LogLevel.Information,
            Message = "[PSYCH] {HumanId} Emotion:{Emotion} V:{Valence:+0.00;-0.00} A:{Arousal:F2} D:{Dominance:F2} Stress:{Stress:F1} CogLoad:{CogLoad:F1} Mood:{MoodBaseline:F1} Social:{NeedSocial:F1} Intimacy:{NeedIntimacy:F1} Achieve:{NeedAchievement:F1} Care:{NeedCare:F1} Safety:{NeedSafety:F1} Sick:{SicknessWithdraw}")]
        public static partial void PsychologySnapshot(
            this ILogger logger,
            string HumanId,
            string Emotion,
            double Valence,
            double Arousal,
            double Dominance,
            double Stress,
            double CogLoad,
            double MoodBaseline,
            double NeedSocial,
            double NeedIntimacy,
            double NeedAchievement,
            double NeedCare,
            double NeedSafety,
            bool SicknessWithdraw);

        /// <summary>
        /// Psychological impact of a nightmare — stress rose, valence fell.
        /// </summary>
        /// <remarks>
        /// Differs from <see cref="SleepNightmare"/> (1108) — that logs the OCCURRENCE of a nightmare
        /// v <c>DefaultSleepSession</c>. Tato metoda loguje EFEKT na psychiku v
        /// <c>DefaultPsychologyEngine</c>.
        /// </remarks>
        [LoggerMessage(
            EventId = 5101,
            Level = LogLevel.Debug,
            Message = "[PSYCH/NIGHTMARE] {HumanId} Noční můra → stres +{StressSpike:F1}, valence -{ValencePenalty:F2}.")]
        public static partial void PsychNightmareEffect(
            this ILogger logger,
            string HumanId,
            double StressSpike,
            double ValencePenalty);

        /// <summary>Poor-quality sleep raised stress.</summary>
        [LoggerMessage(
            EventId = 5102,
            Level = LogLevel.Debug,
            Message = "[PSYCH/SLEEP] Nekvalitní spánek (kvalita={Quality:F0}) → stres +{StressDelta:F1}.")]
        public static partial void PsychSleepInterrupted(this ILogger logger, double Quality, double StressDelta);

        /// <summary>Dominant emotion changed — transition with VAD context.</summary>
        [LoggerMessage(
            EventId = 5103,
            Level = LogLevel.Information,
            Message = "[PSYCH/EMOTION] {HumanId} {OldEmotion}->{NewEmotion} V:{Valence:+0.00;-0.00} A:{Arousal:F2} stress={Stress:F1}")]
        public static partial void EmotionTransition(
            this ILogger logger, string HumanId,
            string OldEmotion, string NewEmotion,
            double Valence, double Arousal, double Stress);

        /// <summary>MoodBaseline shifted significantly (delta > 5 points).</summary>
        [LoggerMessage(
            EventId = 5104,
            Level = LogLevel.Debug,
            Message = "[PSYCH/MOOD] {HumanId} MoodBaseline {OldBaseline:F1}->{NewBaseline:F1} (Δ={Delta:+0.0;-0.0})")]
        public static partial void MoodBaselineShifted(
            this ILogger logger, string HumanId,
            double OldBaseline, double NewBaseline, double Delta);

        /// <summary>AllostaticLoad crossed a critical threshold (60 or 80).</summary>
        [LoggerMessage(
            EventId = 5105,
            Level = LogLevel.Information,
            Message = "[PSYCH/ALLOSTATIC] {HumanId} AllostaticLoad crossed {Threshold:F0}: {OldLoad:F1}->{NewLoad:F1} (cortisol={Cortisol:F1})")]
        public static partial void AllostaticLoadMilestone(
            this ILogger logger, string HumanId,
            double Threshold, double OldLoad, double NewLoad, double Cortisol);

        #endregion Psychology

        #region Behavior — snapshoty

        /// <summary>Snapshot of the behavioural state — needs and current plan.</summary>
        [LoggerMessage(
            EventId = 5200,
            Level = LogLevel.Information,
            Message = "[BEHAV] {HumanId} Plan:{Plan} Rest:{Rest:F1} Food:{Food:F1} Water:{Water:F1} Belonging:{Belonging:F1} Competence:{Competence:F1} Intimacy:{Intimacy:F1} Intent:{IntentKind} IntentStr:{IntentStrength:F2} IntentCommit:{IntentCommitment}")]
        public static partial void BehaviorSnapshot(
            this ILogger logger,
            string HumanId,
            string Plan,
            double Rest,
            double Food,
            double Water,
            double Belonging,
            double Competence,
            double Intimacy,
            string IntentKind,
            double IntentStrength,
            int IntentCommitment);

        /// <summary>Detail of the selected action — utility score and timing.</summary>
        [LoggerMessage(
            EventId = 5201,
            Level = LogLevel.Debug,
            Message = "[BEHAV/PLAN] {HumanId} Action:{Action} Start:{Start} Duration:{Duration} Utility:{Utility:F3}")]
        public static partial void BehaviorPlan(
            this ILogger logger,
            string HumanId,
            string Action,
            string Start,
            string Duration,
            double Utility);

        #endregion Behavior — snapshoty

        #region SelfConcept & LifeStage — 5300 / 1600–1610

        /// <summary>
        /// Per-tick snapshot of the self-concept: global self-esteem, ideal/perceived
        /// discrepancy, and the perceived vs. ideal Big Five. Both esteem and discrepancy
        /// are slow, stable scalars — useful as an identity time series.
        /// </summary>
        [LoggerMessage(
            EventId = 5300,
            Level = LogLevel.Debug,
            Message = "[SELF] {HumanId} esteem={Esteem:F2} discrepancy={Discrepancy:F2} | perc O:{PercOpen:F2} C:{PercCons:F2} E:{PercExtra:F2} A:{PercAgree:F2} N:{PercNeuro:F2} | ideal E:{IdealExtra:F2} A:{IdealAgree:F2} C:{IdealCons:F2}")]
        public static partial void SelfConceptSnapshot(
            this ILogger logger,
            string HumanId,
            double Esteem,
            double Discrepancy,
            double PercOpen,
            double PercCons,
            double PercExtra,
            double PercAgree,
            double PercNeuro,
            double IdealExtra,
            double IdealAgree,
            double IdealCons);

        /// <summary>Life-stage transition — the character aged into a new developmental stadium.</summary>
        [LoggerMessage(
            EventId = 1600,
            Level = LogLevel.Information,
            Message = "[LIFE] {HumanId} Life stage: {From} → {To}.")]
        public static partial void LifeStageTransition(
            this ILogger logger,
            string HumanId,
            string From,
            string To);

        /// <summary>
        /// A life-evaluation (reappraisal) episode opened on a stage transition — the
        /// midlife/reflective reappraisal window (probabilistic).
        /// </summary>
        [LoggerMessage(
            EventId = 1601,
            Level = LogLevel.Information,
            Message = "[LIFE] {HumanId} Life evaluation episode started on {From} → {To}.")]
        public static partial void LifeEvaluationEpisode(
            this ILogger logger,
            string HumanId,
            string From,
            string To);

        /// <summary>
        /// Theory-of-Mind L2 mutual-knowledge formed — character knows that SharedWith also
        /// knows the ActionKind performed by Subject. Discrete event; logged once per new
        /// common-ground fact.
        /// </summary>
        [LoggerMessage(
            EventId = 1610,
            Level = LogLevel.Information,
            Message = "[TOM/L2] {HumanId} mutual knowledge: subject={Subject} sharedWith={SharedWith} actionKind={ActionKind}")]
        public static partial void MutualKnowledgeFormedLog(
            this ILogger logger,
            string HumanId,
            string Subject,
            string SharedWith,
            string ActionKind);

        #endregion SelfConcept & LifeStage — 5300 / 1600–1610

        #region Interests (RIASEC) — 5400

        /// <summary>
        /// Per-tick snapshot of the RIASEC interest profile — current vs. baseline.
        /// Both Current and Baseline dimensions are logged so the LogReader can chart
        /// drift over time. Values are in [0..1].
        /// </summary>
        [LoggerMessage(
            EventId = 5400,
            Level = LogLevel.Debug,
            Message = "[INTERESTS] {HumanId} R:{Realistic:F3} I:{Investigative:F3} A:{Artistic:F3} S:{Social:F3} E:{Enterprising:F3} C:{Conventional:F3} | base R:{BaseRealistic:F3} I:{BaseInvestigative:F3} A:{BaseArtistic:F3} S:{BaseSocial:F3} E:{BaseEnterprising:F3} C:{BaseConventional:F3}")]
        public static partial void InterestsSnapshot(
            this ILogger logger,
            string HumanId,
            double Realistic,
            double Investigative,
            double Artistic,
            double Social,
            double Enterprising,
            double Conventional,
            double BaseRealistic,
            double BaseInvestigative,
            double BaseArtistic,
            double BaseSocial,
            double BaseEnterprising,
            double BaseConventional);

        #endregion Interests (RIASEC) — 5400

        #region Behavior — rozhodování

        /// <summary>An action candidate with its computed utility — logged during action selection.</summary>
        [LoggerMessage(
            EventId = 1000,
            Level = LogLevel.Debug,
            Message = "[BEHAV/CAND] {HumanId} Action:{Action} Utility:{Utility:F3}")]
        public static partial void BehaviorCandidate(
            this ILogger logger,
            string HumanId,
            string Action,
            double Utility);

        /// <summary>Result of action selection — which action was chosen.</summary>
        [LoggerMessage(
            EventId = 1001,
            Level = LogLevel.Information,
            Message = "[BEHAV/DECISION] {HumanId} → {Action} (utility: {Utility:F3})")]
        public static partial void BehaviorDecision(
            this ILogger logger,
            string HumanId,
            string Action,
            double Utility);

        /// <summary>
        /// The action is still running — the engine keeps it and does not replan.
        /// Logged at Debug because it repeats every tick for the whole duration of the action.
        /// </summary>
        [LoggerMessage(
            EventId = 1002,
            Level = LogLevel.Debug,
            Message = "[BEHAV/RUNNING] {HumanId} Akce '{Action}' stále běží, zbývá {Remaining}.")]
        public static partial void BehaviorActionRunning(
            this ILogger logger,
            string HumanId,
            string Action,
            string Remaining);

        /// <summary>
        /// A new action was chosen by the utility function and committed to the outbox.
        /// Logged at Information — every action change matters for debugging behaviour.
        /// </summary>
        [LoggerMessage(
            EventId = 1003,
            Level = LogLevel.Information,
            Message = "[BEHAV/CHOSEN] {HumanId} Nová akce: '{Action}' (utility={Utility:F2}, trvání={Duration}).")]
        public static partial void BehaviorActionChosen(
            this ILogger logger,
            string HumanId,
            string Action,
            double Utility,
            string Duration);

        /// <summary>
        /// Cooldown set for an action — the character cannot repeat it until it expires.
        /// </summary>
        /// <remarks>
        /// Note: <c>SetCooldown</c> has no access to <c>ctx</c>, so <c>HumanId</c>
        /// must be passed explicitly as a parameter, or the method moved to where ctx exists.
        /// </remarks>
        [LoggerMessage(
            EventId = 1004,
            Level = LogLevel.Debug,
            Message = "[BEHAV/COOLDOWN] {HumanId} Cooldown '{Action}': {Hours}h.")]
        public static partial void BehaviorCooldownSet(
            this ILogger logger,
            string HumanId,
            string Action,
            double Hours);

        /// <summary>A new behavioural intent was selected.</summary>
        [LoggerMessage(
            EventId = 1005,
            Level = LogLevel.Debug,
            Message = "[BEHAV/INTENT] {HumanId} intent selected {IntentKind} -> {Action} (score={Score:F2}).")]
        public static partial void BehaviorIntentSelected(
            this ILogger logger,
            string HumanId,
            string IntentKind,
            string Action,
            double Score);

        /// <summary>The current intent was retained for another tick (hysteresis).</summary>
        [LoggerMessage(
            EventId = 1006,
            Level = LogLevel.Debug,
            Message = "[BEHAV/INTENT] {HumanId} intent retained {IntentKind} -> {Action} (score={Score:F2}).")]
        public static partial void BehaviorIntentRetained(
            this ILogger logger,
            string HumanId,
            string IntentKind,
            string Action,
            double Score);

        /// <summary>The intent switched to a different direction.</summary>
        [LoggerMessage(
            EventId = 1007,
            Level = LogLevel.Debug,
            Message = "[BEHAV/INTENT] {HumanId} intent switched {IntentKind} -> {Action} (score={Score:F2}).")]
        public static partial void BehaviorIntentSwitched(
            this ILogger logger,
            string HumanId,
            string IntentKind,
            string Action,
            double Score);

        /// <summary>The current intent expired.</summary>
        [LoggerMessage(
            EventId = 1008,
            Level = LogLevel.Debug,
            Message = "[BEHAV/INTENT] {HumanId} intent expired {IntentKind}.")]
        public static partial void BehaviorIntentExpired(
            this ILogger logger,
            string HumanId,
            string IntentKind);

        /// <summary>An emergency physiological need overrode the current intent.</summary>
        [LoggerMessage(
            EventId = 1009,
            Level = LogLevel.Debug,
            Message = "[BEHAV/INTENT] {HumanId} emergency override {IntentKind} -> {Action} (score={Score:F2}).")]
        public static partial void BehaviorIntentEmergencyOverride(
            this ILogger logger,
            string HumanId,
            string IntentKind,
            string Action,
            double Score);

        /// <summary>An intent bias was applied to a behaviour candidate.</summary>
        [LoggerMessage(
            EventId = 1010,
            Level = LogLevel.Debug,
            Message = "[BEHAV/INTENT] {HumanId} bias applied to {Action}: +{Bias:F2}.")]
        public static partial void BehaviorIntentBiasApplied(
            this ILogger logger,
            string HumanId,
            string Action,
            double Bias);

        /// <summary>A habit trace was reinforced (learned) for an action.</summary>
        [LoggerMessage(
            EventId = 1011,
            Level = LogLevel.Debug,
            Message = "[BEHAV/HABIT] {HumanId} learned {Action} cue={Cue} surface={Surface} time={TimeBand} strength {BeforeStrength:F3}->{AfterStrength:F3} learn={Learning:F3} cueFit={CueFit:F2} relief={ReliefFit:F2} coping={CopingFit:F2} constraint={ConstraintPenalty:F2} tendency={Tendency} reps={RepetitionCount}.")]
        public static partial void BehaviorHabitLearned(
            this ILogger logger,
            string HumanId,
            string Action,
            string Cue,
            string Surface,
            string TimeBand,
            double BeforeStrength,
            double AfterStrength,
            double Learning,
            double CueFit,
            double ReliefFit,
            double CopingFit,
            double ConstraintPenalty,
            string Tendency,
            int RepetitionCount);

        /// <summary>Habit traces decayed over elapsed time.</summary>
        [LoggerMessage(
            EventId = 1012,
            Level = LogLevel.Debug,
            Message = "[BEHAV/HABIT] {HumanId} decay days={Days:F3} retention={Retention:F4} traces {BeforeCount}->{AfterCount} removed={RemovedCount}.")]
        public static partial void BehaviorHabitDecayed(
            this ILogger logger,
            string HumanId,
            double Days,
            double Retention,
            int BeforeCount,
            int AfterCount,
            int RemovedCount);

        /// <summary>Excess habit traces were pruned to the configured maximum.</summary>
        [LoggerMessage(
            EventId = 1013,
            Level = LogLevel.Debug,
            Message = "[BEHAV/HABIT] {HumanId} pruned traces {BeforeCount}->{AfterCount} max={MaxTraces}.")]
        public static partial void BehaviorHabitPruned(
            this ILogger logger,
            string HumanId,
            int BeforeCount,
            int AfterCount,
            int MaxTraces);

        /// <summary>A learned-habit bias was applied to a candidate's utility.</summary>
        [LoggerMessage(
            EventId = 1014,
            Level = LogLevel.Debug,
            Message = "[BEHAV/HABIT] {HumanId} bias {Action}: utility {BeforeUtility:F3}->{AfterUtility:F3}, applicability={Applicability:F3}, multiplier={Multiplier:F3}, flat={FlatBias:F3}.")]
        public static partial void BehaviorHabitBiasApplied(
            this ILogger logger,
            string HumanId,
            string Action,
            double BeforeUtility,
            double AfterUtility,
            double Applicability,
            double Multiplier,
            double FlatBias);

        /// <summary>Decision dominated by a habit trace (habit contributed >40% of utility).</summary>
        [LoggerMessage(
            EventId = 1015,
            Level = LogLevel.Debug,
            Message = "[BEHAV/HABIT] {HumanId} Habit dominated decision: {Action} (habitBias={HabitBias:F3}, totalUtility={TotalUtility:F3}, ratio={Ratio:F2})")]
        public static partial void HabitDominatedDecision(
            this ILogger logger, string HumanId, string Action,
            double HabitBias, double TotalUtility, double Ratio);

        /// <summary>A behavior need crossed a critical threshold.</summary>
        [LoggerMessage(
            EventId = 1016,
            Level = LogLevel.Information,
            Message = "[BEHAV/NEED] {HumanId} {Need} crossed threshold {Threshold:F0}: {OldValue:F1}->{NewValue:F1}")]
        public static partial void NeedThresholdCrossed(
            this ILogger logger, string HumanId, string Need,
            double Threshold, double OldValue, double NewValue);

        #endregion Behavior — rozhodování

        #region Behavior/Sleep — spánkový subsystém

        /// <summary>A sleep prompt was sent — the character reached the fatigue threshold.</summary>
        [LoggerMessage(
            EventId = 1100,
            Level = LogLevel.Information,
            Message = "[BEHAV/SLEEP] {HumanId} Sleep prompt vyslán (NeedRest={NeedRest:F1}).")]
        public static partial void SleepPromptSent(
            this ILogger logger,
            string HumanId,
            double NeedRest);

        /// <summary>Sleep confirmed — session started.</summary>
        [LoggerMessage(
            EventId = 1101,
            Level = LogLevel.Information,
            Message = "[BEHAV/SLEEP] {HumanId} Spánek zahájen. Délka: {Hours:F1}h.")]
        public static partial void SleepStarted(
            this ILogger logger,
            string HumanId,
            double Hours);

        /// <summary>Shared sleep started — the character sleeps with someone else.</summary>
        [LoggerMessage(
            EventId = 1102,
            Level = LogLevel.Information,
            Message = "[BEHAV/SLEEP] {HumanId} Zahájil sdílený spánek ({Type}) se {Companion}.")]
        public static partial void SharedSleepStarted(
            this ILogger logger,
            string HumanId,
            string Type,
            string Companion);

        /// <summary>Sleep declined by the player — the grace period shortens.</summary>
        [LoggerMessage(
            EventId = 1103,
            Level = LogLevel.Warning,
            Message = "[BEHAV/SLEEP] {HumanId} Spánek odmítnut (#{Count}), grace: {Grace:F1}h.")]
        public static partial void SleepDeclinedByPlayer(
            this ILogger logger,
            string HumanId,
            int Count,
            double Grace);

        /// <summary>Sleep session ended naturally or by interruption.</summary>
        [LoggerMessage(
            EventId = 1104,
            Level = LogLevel.Information,
            Message = "[BEHAV/SLEEP] {HumanId} Sleep session ukončena, cooldown {Cooldown}h.")]
        public static partial void SleepSessionEnded(
            this ILogger logger,
            string HumanId,
            double Cooldown);

        /// <summary>The character woke up — sleep duration and quality.</summary>
        [LoggerMessage(
            EventId = 1105,
            Level = LogLevel.Information,
            Message = "[BEHAV/SLEEP] {HumanId} Probudil se. Délka: {Hours:F2}h, Kvalita: {Quality:F1}, Přerušen: {WasInterrupted}.")]
        public static partial void SleepWokeUp(
            this ILogger logger,
            string HumanId,
            double Hours,
            double Quality,
            bool WasInterrupted);

        /// <summary>Sleep interrupted — cause and current phase.</summary>
        [LoggerMessage(
            EventId = 1106,
            Level = LogLevel.Warning,
            Message = "[BEHAV/SLEEP] {HumanId} Spánek přerušen ({Cause}) ve fázi {Phase}.")]
        public static partial void SleepInterrupted(
            this ILogger logger,
            string HumanId,
            string Cause,
            string Phase);

        /// <summary>Transition between sleep phases.</summary>
        [LoggerMessage(
            EventId = 1107,
            Level = LogLevel.Debug,
            Message = "[BEHAV/SLEEP] {HumanId} Vstoupil do fáze {Phase}.")]
        public static partial void SleepPhaseEntered(
            this ILogger logger,
            string HumanId,
            string Phase);

        /// <summary>Nightmare — interrupts the REM phase.</summary>
        [LoggerMessage(
            EventId = 1108,
            Level = LogLevel.Debug,
            Message = "[BEHAV/SLEEP] {HumanId} Noční můra (stres při usnutí: {StressAtSleep:F1}).")]
        public static partial void SleepNightmare(
            this ILogger logger,
            string HumanId,
            double StressAtSleep);

        /// <summary>Dream — the REM phase passed calmly.</summary>
        [LoggerMessage(
            EventId = 1109,
            Level = LogLevel.Debug,
            Message = "[BEHAV/SLEEP] {HumanId} Sen (seed: {Seed}).")]
        public static partial void SleepDream(
            this ILogger logger,
            string HumanId,
            int Seed);

        /// <summary>Ambush during sleep.</summary>
        [LoggerMessage(
            EventId = 1110,
            Level = LogLevel.Warning,
            Message = "[BEHAV/SLEEP] {HumanId} Přepadení během spánku (fáze: {Phase})!")]
        public static partial void SleepAmbush(
            this ILogger logger,
            string HumanId,
            string Phase);

        /// <summary>Penalty for repeatedly declining sleep — stress rises.</summary>
        [LoggerMessage(
            EventId = 1111,
            Level = LogLevel.Debug,
            Message = "[BEHAV/SLEEP] {HumanId} Sleep grace aktivní — penalizace ×{Penalty:F2} (odmítnutí: {DeclineCount}×).")]
        public static partial void SleepGracePenalty(
            this ILogger logger,
            string HumanId,
            double Penalty,
            int DeclineCount);

        /// <summary>Critical exhaustion bypassed the sleep cooldown.</summary>
        [LoggerMessage(
            EventId = 1112,
            Level = LogLevel.Warning,
            Message = "[SLEEP/EMERGENCY] {HumanId} NeedRest:{NeedRest:F1} Energy:{Energy:F1} — cooldown bypassed")]
        public static partial void SleepEmergencyBypass(
            this ILogger logger,
            string HumanId,
            double NeedRest,
            double Energy);

        /// <summary>
        /// Sleep was blocked by biological needs (hunger or thirst).
        /// The character will eat or drink first.
        /// </summary>
        [LoggerMessage(
            EventId = 1113,
            Level = LogLevel.Debug,
            Message = "[SLEEP/BLOCKED] {HumanId} Hunger:{Hunger:F1} Thirst:{Thirst:F1} — sleep blocked by biology")]
        public static partial void SleepBlockedByBiology(
            this ILogger logger,
            string HumanId,
            double Hunger,
            double Thirst);

        #endregion Behavior/Sleep — spánkový subsystém

        #region Behavior/Interaction — kontext

        /// <summary>The character's context changed — new location, noise, privacy.</summary>
        [LoggerMessage(
            EventId = 1200,
            Level = LogLevel.Information,
            Message = "[BEHAV/INTERACT] {HumanId} Kontext změněn: lokace='{Location}', hluk={Noise:F2}, přeplněnost={Crowding:F2}.")]
        public static partial void InteractionContextChanged(
            this ILogger logger,
            string HumanId,
            string Location,
            double Noise,
            double Crowding);

        /// <summary>
        /// Result of the decision to accept/decline an interaction.
        /// Logs the computed acceptance probability and the outcome.
        /// </summary>
        [LoggerMessage(
            EventId = 1201,
            Level = LogLevel.Information,
            Message = "[BEHAV/INTERACT] {HumanId} {From} → {To}: p(přijetí)={P:F2}, výsledek={Result}.")]
        public static partial void InteractionOutcomeDecided(
            this ILogger logger,
            string HumanId,
            string From,
            string To,
            double P,
            string Result);

        /// <summary>A sexual encounter was proposed — logs intent, reproductive potential and contraception.</summary>
        [LoggerMessage(EventId = 1203, Level = LogLevel.Information, Message = "[BEHAV/INTERACT] {HumanId} {From} -> {To}: {Intent}, {ReprPotential}, {Contraception}")]
        public static partial void SexualEncounterProposed(
            this ILogger logger,
            string HumanId,
            string From,
            string To,
            string Intent,
            string ReprPotential,
            string Contraception);

        /// <summary>Stress and noise caused misattribution — interaction outcome modified.</summary>
        [LoggerMessage(
            EventId = 1204,
            Level = LogLevel.Debug,
            Message = "[BEHAV/INTERACT] {HumanId} Misattribution penalty applied: {From}->{To}, stress={Stress:F1}, noise={Noise:F2}, penalty={Penalty:F2}")]
        public static partial void MisattributionPenaltyApplied(
            this ILogger logger, string HumanId, string From, string To,
            double Stress, double Noise, double Penalty);

        /// <summary>Character committed to interacting with a world object.</summary>
        [LoggerMessage(
            EventId = 1205,
            Level = LogLevel.Information,
            Message = "[BEHAV/OBJ] {HumanId} Object interaction: {ObjectId} kind={Kind} at={LocationId} (utility={Utility:F2})")]
        public static partial void ObjectInteractionCommitted(
            this ILogger logger,
            string HumanId,
            string ObjectId,
            string Kind,
            string LocationId,
            double Utility);

        /// <summary>Character arrived at (or departed) a named location — explicit move action committed.</summary>
        [LoggerMessage(
            EventId = 1206,
            Level = LogLevel.Information,
            Message = "[BEHAV/MOVE] {HumanId} Move: {Action} (from='{From}', utility={Utility:F2})")]
        public static partial void MoveActionCommitted(
            this ILogger logger,
            string HumanId,
            string Action,
            string From,
            double Utility);

        /// <summary>
        /// Norm violation detected pre-commit — score and acceptance penalty computed.
        /// Logged at Debug to avoid noise in production runs.
        /// </summary>
        [LoggerMessage(
            EventId = 1207,
            Level = LogLevel.Debug,
            Message = "[BEHAV/NORM] {HumanId} Norm violation detected: kind={NormKind}, score={Score:F2}, acceptancePenalty={Penalty:F2}")]
        public static partial void NormViolationDetected(
            this ILogger logger,
            string HumanId,
            string NormKind,
            double Score,
            double Penalty);

        /// <summary>
        /// Norm violation shame spike applied — emitted by DefaultPsychologyEngine after the fact.
        /// </summary>
        [LoggerMessage(
            EventId = 1208,
            Level = LogLevel.Information,
            Message = "[BEHAV/NORM] {HumanId} Shame spike: kind={NormKind}, score={Score:F2}, audience={HasAudience}")]
        public static partial void NormViolationShameSpiked(
            this ILogger logger,
            string HumanId,
            string NormKind,
            double Score,
            bool HasAudience);

        /// <summary>
        /// Observer norm reaction event routed to a witness character.
        /// Logged at Debug — one entry per observer per norm violation.
        /// </summary>
        [LoggerMessage(
            EventId = 1209,
            Level = LogLevel.Debug,
            Message = "[BEHAV/NORM] {HumanId} Observer {ObserverId}: reaction={Reaction}, score={Score:F2}")]
        public static partial void ObserverNormReactionRouted(
            this ILogger logger,
            string HumanId,
            string ObserverId,
            string Reaction,
            double Score);

        /// <summary>
        /// Values profile generated for a new character at factory creation.
        /// Logged at Debug — fires once per character lifetime.
        /// </summary>
        [LoggerMessage(
            EventId = 1210,
            Level = LogLevel.Debug,
            Message = "[VALUES] {HumanId} ValuesProfile generated: benevolence={Benevolence:F2}, universalism={Universalism:F2}, achievement={Achievement:F2}, power={Power:F2}")]
        public static partial void ValuesProfileGenerated(
            this ILogger logger,
            string HumanId,
            double Benevolence,
            double Universalism,
            double Achievement,
            double Power);

        /// <summary>
        /// Value congruence violation detected pre-selection — utility modified.
        /// Logged at Debug to avoid noise in production runs.
        /// </summary>
        [LoggerMessage(
            EventId = 1211,
            Level = LogLevel.Debug,
            Message = "[VALUES] {HumanId} Congruence violation: action={ActionName}, congruence={Congruence:F2}, utilityDelta={UtilityDelta:F2}")]
        public static partial void ValueCongruenceViolationDetected(
            this ILogger logger,
            string HumanId,
            string ActionName,
            double Congruence,
            double UtilityDelta);

        /// <summary>
        /// Guilt spike applied to actor's psychology after a value congruence violation.
        /// </summary>
        [LoggerMessage(
            EventId = 1212,
            Level = LogLevel.Information,
            Message = "[VALUES] {HumanId} Guilt spike: action={ActionName}, violatedValue={ViolatedValue}, congruence={Congruence:F2}, deltaValence={DeltaValence:F2}")]
        public static partial void GuiltSpikeApplied(
            this ILogger logger,
            string HumanId,
            string ActionName,
            string ViolatedValue,
            double Congruence,
            double DeltaValence);

        /// <summary>
        /// A held value drifted from lived experience (R4 drift). Logged at Debug.
        /// </summary>
        [LoggerMessage(
            EventId = 1213,
            Level = LogLevel.Debug,
            Message = "[VALUES] {HumanId} value drift: eroded={ErodedValue}, strengthened={StrengthenedValue}, delta={Delta:F3}")]
        public static partial void ValueDrifted(
            this ILogger logger,
            string HumanId,
            string ErodedValue,
            string StrengthenedValue,
            double Delta);

        #endregion Behavior/Interaction — kontext

        #region Memory — epizodická paměť

        /// <summary>
        /// An episode was encoded into memory.
        /// </summary>
        /// <remarks>
        /// Logged at <see cref="LogLevel.Debug"/> — there can be hundreds per tick in the sandbox.
        /// </remarks>
        [LoggerMessage(
            EventId = 3000,
            Level = LogLevel.Debug,
            Message = "[MEM/ENCODE] {HumanId} Zakódována epizoda: '{Tag}' (salience={Salience:F2}, emotion={Emotion}, perceived='{Perceived}', distortion={Distortion:F2}).")]
        public static partial void MemoryEncoded(
            this ILogger logger,
            string HumanId,
            string Tag,
            double Salience,
            string Emotion,
            string Perceived,
            double Distortion);

        /// <summary>Memory consolidation ran — number of reinforced episodes.</summary>
        [LoggerMessage(
            EventId = 3001,
            Level = LogLevel.Information,
            Message = "[MEM/CONSOLIDATE] {HumanId} Konsolidace: posíleno {Count} epizod.")]
        public static partial void MemoryConsolidated(
            this ILogger logger,
            string HumanId,
            int Count);

        /// <summary>Episodic memory drifted during recall (reconsolidation).</summary>
        [LoggerMessage(
            EventId = 3002,
            Level = LogLevel.Debug,
            Message = "[MEM/RECONSOL] {HumanId} Episode '{Tag}' drifted: emotion {OldEmotion}->{NewEmotion}, drift={DriftFraction:F3}")]
        public static partial void MemoryReconsolidated(
            this ILogger logger, string HumanId,
            string Tag, string OldEmotion, string NewEmotion, double DriftFraction);

        /// <summary>SemanticMemory belief updated significantly (delta > 0.1).</summary>
        [LoggerMessage(
            EventId = 3003,
            Level = LogLevel.Debug,
            Message = "[MEM/BELIEF] {HumanId} Belief about {Other}: {Kind} {OldStrength:F2}->{NewStrength:F2} (evidence={EvidenceCount})")]
        public static partial void BeliefUpdated(
            this ILogger logger, string HumanId, string Other,
            string Kind, double OldStrength, double NewStrength, int EvidenceCount);

        #endregion Memory — epizodická paměť

        #region Relationships — vztahy

        /// <summary>Relationship event recieved</summary>
        [LoggerMessage(
            EventId = 2001,
            Level = LogLevel.Information,
            Message = "[REL/EVENT] {HumanId} {EventType}: self={Self}, other={Other}, outcome={Outcome}, detail={Detail}.")]
        public static partial void RelEventReceived(
            this ILogger logger,
            string HumanId,
            string EventType,
            string Self,
            string Other,
            string Outcome,
            string Detail);

        /// <summary>Result of the relationship mutation after handling an event — changed fields before/after.</summary>
        [LoggerMessage(
            EventId = 2002,
            Level = LogLevel.Information,
            Message = "[REL/APPLY] {HumanId} {EventType}: self={Self}, other={Other}, outcome={Outcome}, changes={Changes}.")]
        public static partial void RelEventApplied(
            this ILogger logger,
            string HumanId,
            string EventType,
            string Self,
            string Other,
            string Outcome,
            string Changes);

        /// <summary>A new relationship edge was created — first contact between two characters.</summary>
        [LoggerMessage(
            EventId = 2004,
            Level = LogLevel.Information,
            Message = "[REL/EDGE] {HumanId} Nová hrana: {From} → {To}.")]
        public static partial void RelEdgeCreated(
            this ILogger logger,
            string HumanId,
            string From,
            string To);

        /// <summary>Relationship edge updated after an event — current dimension values.</summary>
        [LoggerMessage(
            EventId = 2005,
            Level = LogLevel.Debug,
            Message = "[REL/EDGE] {HumanId} Hrana {From}→{To}: Like={Like:F1}, Trust={Trust:F1}, Closeness={Closeness:F1}, Comfort={Comfort:F1}, Respect={Respect:F1}, Familiarity={Familiarity:F1}, IntimateAffinity={IntimateAffinity:F1}, SexualInterest={Sexual:F1}, AestheticAttraction={Aesthetic:F1}, PhysicalAttraction={Physical:F1}, Communal={Communal:F1}, Exchange={Exchange:F1}, Residue={Residue:F1}, Responsive={Responsive:F1}, Dominance={Dominance:F1}, Prestige={Prestige:F1}, Contempt={Contempt}")]
        public static partial void RelEdgeUpdated(
            this ILogger logger,
            string HumanId,
            string From,
            string To,
            double Like,
            double Trust,
            double Closeness,
            double Comfort,
            double Respect,
            double Familiarity,
            double IntimateAffinity,
            double Sexual,
            double Aesthetic,
            double Physical,
            double Communal,
            double Exchange,
            double Residue,
            double Responsive,
            double Dominance,
            double Prestige,
            bool Contempt);

        /// <summary>Relationship decay was applied across the character's edges.</summary>
        [LoggerMessage(
            EventId = 2006,
            Level = LogLevel.Debug,
            Message = "[REL/DECAY] {HumanId} Počet hran {EdgesCount} (dny: {Days:F1}).")]
        public static partial void RelDecayApplied(
            this ILogger logger,
            string HumanId,
            int EdgesCount,
            double Days);

        /// <summary>First impression formed — relationship edge initialised from the impression.</summary>
        [LoggerMessage(
            EventId = 2007,
            Level = LogLevel.Information,
            Message = "[REL/IMPRESSION] {HumanId} První dojem: {A} → {B} Like={Like:F1}.")]
        public static partial void RelFirstImpression(
            this ILogger logger,
            string HumanId,
            string A,
            string B,
            double Like);

        /// <summary>Sexual encounter outcome resolved — accepted or declined.</summary>
        [LoggerMessage(
            EventId = 2008,
            Level = LogLevel.Information,
            Message = "[REL/SEX] {HumanId} Sexual encounter {From}->{To}: outcome={Outcome}, intimateAffinity={IntimateAffinity:F1}, sexualInterest={SexualInterest:F1}, closeness={Closeness:F1}")]
        public static partial void SexualEncounterOutcome(
            this ILogger logger, string HumanId, string From, string To,
            string Outcome, double IntimateAffinity, double SexualInterest, double Closeness);

        /// <summary>Per-edge dimension detail for decay — which dims changed and by how much.</summary>
        [LoggerMessage(
            EventId = 2009,
            Level = LogLevel.Debug,
            Message = "[REL/DECAY] {HumanId} Edge {From}->{To}: {Changes}")]
        public static partial void RelDecayDimensionDetail(
            this ILogger logger, string HumanId, string From, string To, string Changes);

        /// <summary>A relationship dimension crossed a significant milestone threshold.</summary>
        [LoggerMessage(
            EventId = 2010,
            Level = LogLevel.Information,
            Message = "[REL/MILESTONE] {HumanId} {From}->{To}: {Dimension} crossed {Threshold:F0} ({OldValue:F1}->{NewValue:F1})")]
        public static partial void RelationshipMilestoneReached(
            this ILogger logger, string HumanId, string From, string To,
            string Dimension, double Threshold, double OldValue, double NewValue);

        /// <summary>Third-party observation changed B's edge toward A.</summary>
        [LoggerMessage(
            EventId = 2011,
            Level = LogLevel.Debug,
            Message = "[REL/THIRD] {Observer} observed {Actor} act on {Target}: {Dimension} {OldValue:F1}->{NewValue:F1} (weight={Weight:F2})")]
        public static partial void ThirdPartyReputationChanged(
            this ILogger logger, string Observer, string Actor, string Target,
            string Dimension, double OldValue, double NewValue, double Weight);

        /// <summary>Jealousy distress applied — TransgressionResidue increased.</summary>
        [LoggerMessage(
            EventId = 2012,
            Level = LogLevel.Information,
            Message = "[REL/JEALOUSY] {HumanId} Jealousy distress: {IntimateActor}->{IntimateTarget} observed, transgressionResidue {OldResidue:F2}->{NewResidue:F2}")]
        public static partial void JealousyDistressApplied(
            this ILogger logger, string HumanId, string IntimateActor, string IntimateTarget,
            double OldResidue, double NewResidue);

        /// <summary>A touch interaction outcome was decided — logs level, acceptance probability and result.</summary>
        [LoggerMessage(
            EventId = 1202,
            Level = LogLevel.Information,
            Message = "[BEHAV/TOUCH] {HumanId} {From} → {To}: level={Level}, p(přijetí)={P:F2}, výsledek={Result}.")]
        public static partial void TouchOutcomeDecided(
            this ILogger logger,
            string HumanId,
            string From,
            string To,
            string Level,
            double P,
            string Result);

        /// <summary>
        /// One-way observation — observer noticed target, target was unaware.
        /// Seeds a weak one-sided edge on the observer only.
        /// </summary>
        [LoggerMessage(
            EventId = 2013,
            Level = LogLevel.Debug,
            Message = "[REL/ONEWAY] {HumanId} Jednostranné pozorování: {Observer} → {Target} " +
                      "Like={Like:F1} Attraction={Attraction:F1}.")]
        public static partial void RelOneWayObservation(
            this ILogger logger,
            string HumanId,
            string Observer,
            string Target,
            double Like,
            double Attraction);

        /// <summary>
        /// Investment-model integrator state for one edge (Rusbult; debug diagnostics only).
        /// Logs the recomputed Commitment, accumulated InvestmentSize and derived CL_alt.
        /// </summary>
        [LoggerMessage(
            EventId = 2014,
            Level = LogLevel.Debug,
            Message = "[REL/INVEST] {HumanId} {A} → {B}: commitment={Commitment:F1} (cíl {Target:F1}) " +
                      "investice={Investment:F1} alternativa={Alternative:F1}.")]
        public static partial void RelInvestmentModel(
            this ILogger logger,
            string HumanId,
            string A,
            string B,
            double Commitment,
            double Target,
            double Investment,
            double Alternative);

        /// <summary>
        /// Partner-edge commitment fell below the dissolution threshold (Rusbult leave point).
        /// Emitted once per downward crossing alongside <see cref="GameEngineTools.Characters.Engines.Relationships.RelationshipDissolutionConsidered"/>.
        /// </summary>
        [LoggerMessage(
            EventId = 2015,
            Level = LogLevel.Debug,
            Message = "[REL/DISSOLUTION] {HumanId} {A} → {B}: zvažuje rozchod, commitment={Commitment:F1}.")]
        public static partial void RelDissolutionConsidered(
            this ILogger logger,
            string HumanId,
            string A,
            string B,
            double Commitment);

        #endregion Relationships — vztahy

        #region DailySchedule — 1400–1499

        /// <summary>A new calendar day's slots have been registered with the scheduler.</summary>
        [LoggerMessage(
            EventId = 1400,
            Level = LogLevel.Debug,
            Message = "[SCHEDULE] {HumanId} Day {DayIndex} registered: {SlotCount} slots")]
        public static partial void ScheduleDayRegistered(
            this ILogger logger,
            string HumanId,
            int SlotCount,
            long DayIndex);

        /// <summary>A scheduled slot has fired and the action window is now active.</summary>
        [LoggerMessage(
            EventId = 1401,
            Level = LogLevel.Debug,
            Message = "[SCHEDULE] {HumanId} Slot triggered: {SlotId} → {Action} @ {Location}")]
        public static partial void ScheduleSlotTriggered(
            this ILogger logger,
            string HumanId,
            string SlotId,
            string Action,
            string Location);

        /// <summary>A slot bias has been applied to a behavior candidate.</summary>
        [LoggerMessage(
            EventId = 1402,
            Level = LogLevel.Debug,
            Message = "[SCHEDULE] {HumanId} Bias +{Bias:F2} on {Action} from slot {SlotId}")]
        public static partial void ScheduleSlotBiasApplied(
            this ILogger logger,
            string HumanId,
            double Bias,
            string Action,
            string SlotId);

        /// <summary>A skippable slot was ignored due to high stress or low energy.</summary>
        [LoggerMessage(
            EventId = 1403,
            Level = LogLevel.Debug,
            Message = "[SCHEDULE] {HumanId} Slot {SlotId} skipped (stress={Stress:F1}, energy={Energy:F1})")]
        public static partial void ScheduleSlotSkipped(
            this ILogger logger,
            string HumanId,
            string SlotId,
            double Stress,
            double Energy);

        /// <summary>Daily schedule seeded from occupation at character creation.</summary>
        [LoggerMessage(
            EventId = 1404,
            Level = LogLevel.Information,
            Message = "[SCHEDULE] {HumanId} Schedule seeded: occupation={Occupation}, slots={SlotCount}")]
        public static partial void ScheduleSeeded(
            this ILogger logger,
            string HumanId,
            string Occupation,
            int SlotCount);

        #endregion DailySchedule — 1400–1499

        #region Goals — 1300–1399

        /// <summary>Goal activated — new persistent goal entered the active list.</summary>
        [LoggerMessage(
            EventId = 1300,
            Level = LogLevel.Information,
            Message = "[GOAL] {HumanId} Goal activated: {Kind} (origin={Origin}, salience={Salience:F2})")]
        public static partial void GoalActivated(
            this ILogger logger,
            string HumanId,
            string Kind,
            string Origin,
            double Salience);

        /// <summary>Goal salience or progress changed meaningfully.</summary>
        [LoggerMessage(
            EventId = 1301,
            Level = LogLevel.Debug,
            Message = "[GOAL] {HumanId} {Kind} salience {OldSalience:F2}->{NewSalience:F2} progress {OldProgress:F2}->{NewProgress:F2}")]
        public static partial void GoalProgressed(
            this ILogger logger,
            string HumanId,
            string Kind,
            double OldSalience,
            double NewSalience,
            double OldProgress,
            double NewProgress);

        /// <summary>Goal resolved — completed, abandoned, faded, or displaced.</summary>
        [LoggerMessage(
            EventId = 1302,
            Level = LogLevel.Information,
            Message = "[GOAL] {HumanId} Goal resolved: {Kind} → {Resolution} (progress={Progress:F2}, frustration={Frustration:F2})")]
        public static partial void GoalResolved(
            this ILogger logger,
            string HumanId,
            string Kind,
            string Resolution,
            double Progress,
            double Frustration);

        /// <summary>Goal bias applied to a behavior candidate.</summary>
        [LoggerMessage(
            EventId = 1303,
            Level = LogLevel.Debug,
            Message = "[GOAL] {HumanId} Bias applied to {Action}: +{Bias:F2} from goal {Kind} (salience={Salience:F2})")]
        public static partial void GoalBiasApplied(
            this ILogger logger,
            string HumanId,
            string Action,
            double Bias,
            string Kind,
            double Salience);

        /// <summary>Goal seeded from personality at character creation.</summary>
        [LoggerMessage(
            EventId = 1304,
            Level = LogLevel.Debug,
            Message = "[GOAL] {HumanId} Seeded {Kind} from personality (salience={Salience:F2})")]
        public static partial void GoalSeededFromPersonality(
            this ILogger logger,
            string HumanId,
            string Kind,
            double Salience);

        #endregion Goals — 1300–1399

        #region World Objects — 1500–1599

        /// <summary>
        /// Character used a world object in place — records what was consumed, what affordances fired, and total satisfaction.
        /// Logged at Information so it appears in production runs alongside action decisions.
        /// </summary>
        [LoggerMessage(
            EventId = 1500,
            Level = LogLevel.Information,
            Message = "[OBJ/USE] {HumanId} used {ObjectId} ({DisplayName}) at {LocationId}: affordances={Affordances} sat={Satisfaction:F2} consumed={WasConsumed}")]
        public static partial void ObjectUsed(
            this ILogger logger,
            string HumanId,
            string ObjectId,
            string DisplayName,
            string LocationId,
            string Affordances,
            double Satisfaction,
            bool WasConsumed);

        /// <summary>
        /// A consumed world object was restored by the respawn scheduler.
        /// Logged at Debug — fires once per object per respawn cycle.
        /// No HumanId — this is a world-level event, not character-scoped.
        /// </summary>
        [LoggerMessage(
            EventId = 1501,
            Level = LogLevel.Debug,
            Message = "[OBJ/RESPAWN] {ObjectId} ({DisplayName}) at {LocationId} respawned after {ElapsedMinutes:F0}min")]
        public static partial void ObjectRespawned(
            this ILogger logger,
            string ObjectId,
            string DisplayName,
            string LocationId,
            double ElapsedMinutes);

        #endregion World Objects — 1500–1599

        #region Scheduler a infrastruktura

        /// <summary>The scheduler was started.</summary>
        [LoggerMessage(EventId = 4100, Level = LogLevel.Information, Message = "Scheduler: started")]
        public static partial void SchedulerStarted(this ILogger logger);

        /// <summary>The scheduler ran a tick.</summary>
        [LoggerMessage(EventId = 4101, Level = LogLevel.Information, Message = "Scheduler: run tick")]
        public static partial void SchedulerRun(this ILogger logger);

        /// <summary>The scheduler had nothing to process — idle.</summary>
        [LoggerMessage(EventId = 4102, Level = LogLevel.Debug, Message = "Scheduler: idle")]
        public static partial void SchedulerIdle(this ILogger logger);

        /// <summary>The scheduler failed — exception caught.</summary>
        [LoggerMessage(EventId = 4103, Level = LogLevel.Error, Message = "Scheduler: failed")]
        public static partial void SchedulerFailed(this ILogger logger, Exception ex);

        #endregion Scheduler a infrastruktura

        /// <summary>A MoveTo request found no location for the needed category via memory or provider.</summary>
        [LoggerMessage(EventId = 10001, Level = LogLevel.Debug, Message = "[MoveTo] {CharId} needs {Category} but found no location via memory or provider.")]
        public static partial void SceneMoveToFailed(this ILogger logger, string CharId, string Category);

        /// <summary>A MoveTo of the given type was requested but no suitable location exists.</summary>
        [LoggerMessage(EventId = 10002, Level = LogLevel.Debug, Message = "[MoveTo] {CharId} requested {Type} but no suitable location exists. Current location: {CurrentLocation}.")]
        public static partial void SceneMoveToRequested(this ILogger logger, string CharId, string Type, string CurrentLocation);

        /// <summary>
        /// A <c>ReachOut</c> action was routed by the scene orchestrator to a concrete target.
        /// Captures the chosen speech act and the relationship context that drove the selection,
        /// so the social-behaviour decision is recoverable in the LogReader (not just the
        /// resulting interaction).
        /// </summary>
        [LoggerMessage(
            EventId = 10003,
            Level = LogLevel.Information,
            Message = "[ReachOut] {CharId} -> {TargetId}: act={Act}, familiarity={Familiarity:F1}, trust={Trust:F1}, comfort={Comfort:F1}, closeness={Closeness:F1}, romantic={Romantic:F1}, privacy={HasPrivacy}")]
        public static partial void SceneReachOutRouted(
            this ILogger logger,
            string CharId,
            string TargetId,
            string Act,
            double Familiarity,
            double Trust,
            double Comfort,
            double Closeness,
            double Romantic,
            bool HasPrivacy);
    }
}
